# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: o11y_one/agentic/v1/trace_view.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import o11y_one.agentic.v1.agent_run_pb2 as o11y__one_dot_agentic_dot_v1_dot_agent__run__pb2
import o11y_one.agentic.v1.artifact_pb2 as o11y__one_dot_agentic_dot_v1_dot_artifact__pb2
import o11y_one.agentic.v1.trace_view_pb2 as o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2


class AgenticTraceViewService(Protocol):
    async def get_agent_trace_detail(self, request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentTraceDetailRequest, ctx: RequestContext) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentTraceDetailResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_agent_trace_spans(self, request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTraceSpansRequest, ctx: RequestContext) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTraceSpansResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def confirm_agent_run_grouping(self, request: o11y__one_dot_agentic_dot_v1_dot_agent__run__pb2.ConfirmAgentRunGroupingRequest, ctx: RequestContext) -> o11y__one_dot_agentic_dot_v1_dot_agent__run__pb2.ConfirmAgentRunGroupingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_agent_runs(self, request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunsRequest, ctx: RequestContext) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_agent_traces(self, request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTracesRequest, ctx: RequestContext) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTracesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_agent_evidence_graph(self, request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentEvidenceGraphRequest, ctx: RequestContext) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentEvidenceGraphResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_agent_run(self, request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentRunRequest, ctx: RequestContext) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentRunResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_agent_run_events(self, request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunEventsRequest, ctx: RequestContext) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunEventsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def link_external_artifact(self, request: o11y__one_dot_agentic_dot_v1_dot_artifact__pb2.LinkExternalArtifactRequest, ctx: RequestContext) -> o11y__one_dot_agentic_dot_v1_dot_artifact__pb2.LinkExternalArtifactResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def revoke_external_artifact_link(self, request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.RevokeExternalArtifactLinkRequest, ctx: RequestContext) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.RevokeExternalArtifactLinkResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def resolve_external_artifact_link(self, request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ResolveExternalArtifactLinkRequest, ctx: RequestContext) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ResolveExternalArtifactLinkResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AgenticTraceViewServiceASGIApplication(ConnectASGIApplication[AgenticTraceViewService]):
    def __init__(self, service: AgenticTraceViewService | AsyncGenerator[AgenticTraceViewService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/o11y_one.agentic.v1.AgenticTraceViewService/GetAgentTraceDetail": Endpoint.unary(
                    method=MethodInfo(
                        name="GetAgentTraceDetail",
                        service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                        input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentTraceDetailRequest,
                        output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentTraceDetailResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_agent_trace_detail,
                ),
                "/o11y_one.agentic.v1.AgenticTraceViewService/ListAgentTraceSpans": Endpoint.unary(
                    method=MethodInfo(
                        name="ListAgentTraceSpans",
                        service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                        input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTraceSpansRequest,
                        output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTraceSpansResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_agent_trace_spans,
                ),
                "/o11y_one.agentic.v1.AgenticTraceViewService/ConfirmAgentRunGrouping": Endpoint.unary(
                    method=MethodInfo(
                        name="ConfirmAgentRunGrouping",
                        service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                        input=o11y__one_dot_agentic_dot_v1_dot_agent__run__pb2.ConfirmAgentRunGroupingRequest,
                        output=o11y__one_dot_agentic_dot_v1_dot_agent__run__pb2.ConfirmAgentRunGroupingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.confirm_agent_run_grouping,
                ),
                "/o11y_one.agentic.v1.AgenticTraceViewService/ListAgentRuns": Endpoint.unary(
                    method=MethodInfo(
                        name="ListAgentRuns",
                        service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                        input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunsRequest,
                        output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_agent_runs,
                ),
                "/o11y_one.agentic.v1.AgenticTraceViewService/ListAgentTraces": Endpoint.unary(
                    method=MethodInfo(
                        name="ListAgentTraces",
                        service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                        input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTracesRequest,
                        output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTracesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_agent_traces,
                ),
                "/o11y_one.agentic.v1.AgenticTraceViewService/GetAgentEvidenceGraph": Endpoint.unary(
                    method=MethodInfo(
                        name="GetAgentEvidenceGraph",
                        service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                        input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentEvidenceGraphRequest,
                        output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentEvidenceGraphResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_agent_evidence_graph,
                ),
                "/o11y_one.agentic.v1.AgenticTraceViewService/GetAgentRun": Endpoint.unary(
                    method=MethodInfo(
                        name="GetAgentRun",
                        service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                        input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentRunRequest,
                        output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentRunResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_agent_run,
                ),
                "/o11y_one.agentic.v1.AgenticTraceViewService/ListAgentRunEvents": Endpoint.unary(
                    method=MethodInfo(
                        name="ListAgentRunEvents",
                        service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                        input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunEventsRequest,
                        output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunEventsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_agent_run_events,
                ),
                "/o11y_one.agentic.v1.AgenticTraceViewService/LinkExternalArtifact": Endpoint.unary(
                    method=MethodInfo(
                        name="LinkExternalArtifact",
                        service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                        input=o11y__one_dot_agentic_dot_v1_dot_artifact__pb2.LinkExternalArtifactRequest,
                        output=o11y__one_dot_agentic_dot_v1_dot_artifact__pb2.LinkExternalArtifactResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.link_external_artifact,
                ),
                "/o11y_one.agentic.v1.AgenticTraceViewService/RevokeExternalArtifactLink": Endpoint.unary(
                    method=MethodInfo(
                        name="RevokeExternalArtifactLink",
                        service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                        input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.RevokeExternalArtifactLinkRequest,
                        output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.RevokeExternalArtifactLinkResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.revoke_external_artifact_link,
                ),
                "/o11y_one.agentic.v1.AgenticTraceViewService/ResolveExternalArtifactLink": Endpoint.unary(
                    method=MethodInfo(
                        name="ResolveExternalArtifactLink",
                        service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                        input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ResolveExternalArtifactLinkRequest,
                        output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ResolveExternalArtifactLinkResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.resolve_external_artifact_link,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/o11y_one.agentic.v1.AgenticTraceViewService"


class AgenticTraceViewServiceClient(ConnectClient):
    async def get_agent_trace_detail(
        self,
        request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentTraceDetailRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentTraceDetailResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetAgentTraceDetail",
                service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentTraceDetailRequest,
                output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentTraceDetailResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_agent_trace_spans(
        self,
        request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTraceSpansRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTraceSpansResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListAgentTraceSpans",
                service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTraceSpansRequest,
                output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTraceSpansResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def confirm_agent_run_grouping(
        self,
        request: o11y__one_dot_agentic_dot_v1_dot_agent__run__pb2.ConfirmAgentRunGroupingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> o11y__one_dot_agentic_dot_v1_dot_agent__run__pb2.ConfirmAgentRunGroupingResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ConfirmAgentRunGrouping",
                service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                input=o11y__one_dot_agentic_dot_v1_dot_agent__run__pb2.ConfirmAgentRunGroupingRequest,
                output=o11y__one_dot_agentic_dot_v1_dot_agent__run__pb2.ConfirmAgentRunGroupingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_agent_runs(
        self,
        request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListAgentRuns",
                service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunsRequest,
                output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_agent_traces(
        self,
        request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTracesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTracesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListAgentTraces",
                service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTracesRequest,
                output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTracesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_agent_evidence_graph(
        self,
        request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentEvidenceGraphRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentEvidenceGraphResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetAgentEvidenceGraph",
                service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentEvidenceGraphRequest,
                output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentEvidenceGraphResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_agent_run(
        self,
        request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentRunRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentRunResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetAgentRun",
                service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentRunRequest,
                output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentRunResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_agent_run_events(
        self,
        request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunEventsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunEventsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListAgentRunEvents",
                service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunEventsRequest,
                output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunEventsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def link_external_artifact(
        self,
        request: o11y__one_dot_agentic_dot_v1_dot_artifact__pb2.LinkExternalArtifactRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> o11y__one_dot_agentic_dot_v1_dot_artifact__pb2.LinkExternalArtifactResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="LinkExternalArtifact",
                service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                input=o11y__one_dot_agentic_dot_v1_dot_artifact__pb2.LinkExternalArtifactRequest,
                output=o11y__one_dot_agentic_dot_v1_dot_artifact__pb2.LinkExternalArtifactResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def revoke_external_artifact_link(
        self,
        request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.RevokeExternalArtifactLinkRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.RevokeExternalArtifactLinkResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RevokeExternalArtifactLink",
                service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.RevokeExternalArtifactLinkRequest,
                output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.RevokeExternalArtifactLinkResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def resolve_external_artifact_link(
        self,
        request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ResolveExternalArtifactLinkRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ResolveExternalArtifactLinkResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ResolveExternalArtifactLink",
                service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ResolveExternalArtifactLinkRequest,
                output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ResolveExternalArtifactLinkResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class AgenticTraceViewServiceSync(Protocol):
    def get_agent_trace_detail(self, request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentTraceDetailRequest, ctx: RequestContext) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentTraceDetailResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_agent_trace_spans(self, request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTraceSpansRequest, ctx: RequestContext) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTraceSpansResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def confirm_agent_run_grouping(self, request: o11y__one_dot_agentic_dot_v1_dot_agent__run__pb2.ConfirmAgentRunGroupingRequest, ctx: RequestContext) -> o11y__one_dot_agentic_dot_v1_dot_agent__run__pb2.ConfirmAgentRunGroupingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_agent_runs(self, request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunsRequest, ctx: RequestContext) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_agent_traces(self, request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTracesRequest, ctx: RequestContext) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTracesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_agent_evidence_graph(self, request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentEvidenceGraphRequest, ctx: RequestContext) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentEvidenceGraphResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_agent_run(self, request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentRunRequest, ctx: RequestContext) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentRunResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_agent_run_events(self, request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunEventsRequest, ctx: RequestContext) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunEventsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def link_external_artifact(self, request: o11y__one_dot_agentic_dot_v1_dot_artifact__pb2.LinkExternalArtifactRequest, ctx: RequestContext) -> o11y__one_dot_agentic_dot_v1_dot_artifact__pb2.LinkExternalArtifactResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def revoke_external_artifact_link(self, request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.RevokeExternalArtifactLinkRequest, ctx: RequestContext) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.RevokeExternalArtifactLinkResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def resolve_external_artifact_link(self, request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ResolveExternalArtifactLinkRequest, ctx: RequestContext) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ResolveExternalArtifactLinkResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AgenticTraceViewServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: AgenticTraceViewServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            endpoints={
                "/o11y_one.agentic.v1.AgenticTraceViewService/GetAgentTraceDetail": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetAgentTraceDetail",
                        service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                        input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentTraceDetailRequest,
                        output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentTraceDetailResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_agent_trace_detail,
                ),
                "/o11y_one.agentic.v1.AgenticTraceViewService/ListAgentTraceSpans": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListAgentTraceSpans",
                        service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                        input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTraceSpansRequest,
                        output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTraceSpansResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_agent_trace_spans,
                ),
                "/o11y_one.agentic.v1.AgenticTraceViewService/ConfirmAgentRunGrouping": EndpointSync.unary(
                    method=MethodInfo(
                        name="ConfirmAgentRunGrouping",
                        service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                        input=o11y__one_dot_agentic_dot_v1_dot_agent__run__pb2.ConfirmAgentRunGroupingRequest,
                        output=o11y__one_dot_agentic_dot_v1_dot_agent__run__pb2.ConfirmAgentRunGroupingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.confirm_agent_run_grouping,
                ),
                "/o11y_one.agentic.v1.AgenticTraceViewService/ListAgentRuns": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListAgentRuns",
                        service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                        input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunsRequest,
                        output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_agent_runs,
                ),
                "/o11y_one.agentic.v1.AgenticTraceViewService/ListAgentTraces": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListAgentTraces",
                        service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                        input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTracesRequest,
                        output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTracesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_agent_traces,
                ),
                "/o11y_one.agentic.v1.AgenticTraceViewService/GetAgentEvidenceGraph": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetAgentEvidenceGraph",
                        service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                        input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentEvidenceGraphRequest,
                        output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentEvidenceGraphResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_agent_evidence_graph,
                ),
                "/o11y_one.agentic.v1.AgenticTraceViewService/GetAgentRun": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetAgentRun",
                        service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                        input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentRunRequest,
                        output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentRunResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_agent_run,
                ),
                "/o11y_one.agentic.v1.AgenticTraceViewService/ListAgentRunEvents": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListAgentRunEvents",
                        service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                        input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunEventsRequest,
                        output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunEventsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_agent_run_events,
                ),
                "/o11y_one.agentic.v1.AgenticTraceViewService/LinkExternalArtifact": EndpointSync.unary(
                    method=MethodInfo(
                        name="LinkExternalArtifact",
                        service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                        input=o11y__one_dot_agentic_dot_v1_dot_artifact__pb2.LinkExternalArtifactRequest,
                        output=o11y__one_dot_agentic_dot_v1_dot_artifact__pb2.LinkExternalArtifactResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.link_external_artifact,
                ),
                "/o11y_one.agentic.v1.AgenticTraceViewService/RevokeExternalArtifactLink": EndpointSync.unary(
                    method=MethodInfo(
                        name="RevokeExternalArtifactLink",
                        service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                        input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.RevokeExternalArtifactLinkRequest,
                        output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.RevokeExternalArtifactLinkResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.revoke_external_artifact_link,
                ),
                "/o11y_one.agentic.v1.AgenticTraceViewService/ResolveExternalArtifactLink": EndpointSync.unary(
                    method=MethodInfo(
                        name="ResolveExternalArtifactLink",
                        service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                        input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ResolveExternalArtifactLinkRequest,
                        output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ResolveExternalArtifactLinkResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.resolve_external_artifact_link,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/o11y_one.agentic.v1.AgenticTraceViewService"


class AgenticTraceViewServiceClientSync(ConnectClientSync):
    def get_agent_trace_detail(
        self,
        request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentTraceDetailRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentTraceDetailResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetAgentTraceDetail",
                service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentTraceDetailRequest,
                output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentTraceDetailResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_agent_trace_spans(
        self,
        request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTraceSpansRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTraceSpansResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListAgentTraceSpans",
                service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTraceSpansRequest,
                output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTraceSpansResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def confirm_agent_run_grouping(
        self,
        request: o11y__one_dot_agentic_dot_v1_dot_agent__run__pb2.ConfirmAgentRunGroupingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> o11y__one_dot_agentic_dot_v1_dot_agent__run__pb2.ConfirmAgentRunGroupingResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ConfirmAgentRunGrouping",
                service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                input=o11y__one_dot_agentic_dot_v1_dot_agent__run__pb2.ConfirmAgentRunGroupingRequest,
                output=o11y__one_dot_agentic_dot_v1_dot_agent__run__pb2.ConfirmAgentRunGroupingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_agent_runs(
        self,
        request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListAgentRuns",
                service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunsRequest,
                output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_agent_traces(
        self,
        request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTracesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTracesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListAgentTraces",
                service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTracesRequest,
                output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentTracesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_agent_evidence_graph(
        self,
        request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentEvidenceGraphRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentEvidenceGraphResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetAgentEvidenceGraph",
                service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentEvidenceGraphRequest,
                output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentEvidenceGraphResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_agent_run(
        self,
        request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentRunRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentRunResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetAgentRun",
                service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentRunRequest,
                output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.GetAgentRunResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_agent_run_events(
        self,
        request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunEventsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunEventsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListAgentRunEvents",
                service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunEventsRequest,
                output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ListAgentRunEventsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def link_external_artifact(
        self,
        request: o11y__one_dot_agentic_dot_v1_dot_artifact__pb2.LinkExternalArtifactRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> o11y__one_dot_agentic_dot_v1_dot_artifact__pb2.LinkExternalArtifactResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="LinkExternalArtifact",
                service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                input=o11y__one_dot_agentic_dot_v1_dot_artifact__pb2.LinkExternalArtifactRequest,
                output=o11y__one_dot_agentic_dot_v1_dot_artifact__pb2.LinkExternalArtifactResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def revoke_external_artifact_link(
        self,
        request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.RevokeExternalArtifactLinkRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.RevokeExternalArtifactLinkResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RevokeExternalArtifactLink",
                service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.RevokeExternalArtifactLinkRequest,
                output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.RevokeExternalArtifactLinkResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def resolve_external_artifact_link(
        self,
        request: o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ResolveExternalArtifactLinkRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ResolveExternalArtifactLinkResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ResolveExternalArtifactLink",
                service_name="o11y_one.agentic.v1.AgenticTraceViewService",
                input=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ResolveExternalArtifactLinkRequest,
                output=o11y__one_dot_agentic_dot_v1_dot_trace__view__pb2.ResolveExternalArtifactLinkResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
