# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: o11y_one/common/v1/common.proto
# Protobuf Python Version: 7.36.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    1,
    '',
    'o11y_one/common/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fo11y_one/common/v1/common.proto\x12\x12o11y_one.common.v1\"g\n\rPageRequestV1\x12\x19\n\x05limit\x18\x01 \x01(\rH\x00R\x05limit\x88\x01\x01\x12\"\n\npage_token\x18\x02 \x01(\tH\x01R\tpageToken\x88\x01\x01\x42\x08\n\x06_limitB\r\n\x0b_page_token\"\xa4\x02\n\x0ePageResponseV1\x12+\n\x0fnext_page_token\x18\x01 \x01(\tH\x00R\rnextPageToken\x88\x01\x01\x12\x19\n\x08has_more\x18\x02 \x01(\x08R\x07hasMore\x12\x1f\n\x0btotal_count\x18\x03 \x01(\x04R\ntotalCount\x12)\n\x10\x63ursor_semantics\x18\x04 \x01(\tR\x0f\x63ursorSemantics\x12\x36\n\x17total_count_approximate\x18\x05 \x01(\x08R\x15totalCountApproximate\x12\x32\n\x15total_count_semantics\x18\x06 \x01(\tR\x13totalCountSemanticsB\x12\n\x10_next_page_token\"a\n\nSortSpecV1\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x41\n\tdirection\x18\x02 \x01(\x0e\x32#.o11y_one.common.v1.SortDirectionV1R\tdirection*k\n\x0fSortDirectionV1\x12!\n\x1dSORT_DIRECTION_V1_UNSPECIFIED\x10\x00\x12\x1a\n\x16SORT_DIRECTION_V1_DESC\x10\x01\x12\x19\n\x15SORT_DIRECTION_V1_ASC\x10\x02\x42\xd0\x01\n\x16\x63om.o11y_one.common.v1B\x0b\x43ommonProtoP\x01ZCgithub.com/o11y-one/o11y-one-sdk/gen/go/o11y_one/common/v1;commonv1\xa2\x02\x03OCX\xaa\x02\x11O11yOne.Common.V1\xca\x02\x11O11yOne\\Common\\V1\xe2\x02\x1dO11yOne\\Common\\V1\\GPBMetadata\xea\x02\x13O11yOne::Common::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'o11y_one.common.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.o11y_one.common.v1B\013CommonProtoP\001ZCgithub.com/o11y-one/o11y-one-sdk/gen/go/o11y_one/common/v1;commonv1\242\002\003OCX\252\002\021O11yOne.Common.V1\312\002\021O11yOne\\Common\\V1\342\002\035O11yOne\\Common\\V1\\GPBMetadata\352\002\023O11yOne::Common::V1'
  _globals['_SORTDIRECTIONV1']._serialized_start=554
  _globals['_SORTDIRECTIONV1']._serialized_end=661
  _globals['_PAGEREQUESTV1']._serialized_start=55
  _globals['_PAGEREQUESTV1']._serialized_end=158
  _globals['_PAGERESPONSEV1']._serialized_start=161
  _globals['_PAGERESPONSEV1']._serialized_end=453
  _globals['_SORTSPECV1']._serialized_start=455
  _globals['_SORTSPECV1']._serialized_end=552
# @@protoc_insertion_point(module_scope)
