// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=js"
// @generated from file o11y_one/common/v1/common.proto (package o11y_one.common.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file o11y_one/common/v1/common.proto.
 */
export const file_o11y_one_common_v1_common: GenFile = /*@__PURE__*/
  fileDesc("Ch9vMTF5X29uZS9jb21tb24vdjEvY29tbW9uLnByb3RvEhJvMTF5X29uZS5jb21tb24udjEiVQoNUGFnZVJlcXVlc3RWMRISCgVsaW1pdBgBIAEoDUgAiAEBEhcKCnBhZ2VfdG9rZW4YAiABKAlIAYgBAUIICgZfbGltaXRCDQoLX3BhZ2VfdG9rZW4iwwEKDlBhZ2VSZXNwb25zZVYxEhwKD25leHRfcGFnZV90b2tlbhgBIAEoCUgAiAEBEhAKCGhhc19tb3JlGAIgASgIEhMKC3RvdGFsX2NvdW50GAMgASgEEhgKEGN1cnNvcl9zZW1hbnRpY3MYBCABKAkSHwoXdG90YWxfY291bnRfYXBwcm94aW1hdGUYBSABKAgSHQoVdG90YWxfY291bnRfc2VtYW50aWNzGAYgASgJQhIKEF9uZXh0X3BhZ2VfdG9rZW4iUQoKU29ydFNwZWNWMRILCgNrZXkYASABKAkSNgoJZGlyZWN0aW9uGAIgASgOMiMubzExeV9vbmUuY29tbW9uLnYxLlNvcnREaXJlY3Rpb25WMSprCg9Tb3J0RGlyZWN0aW9uVjESIQodU09SVF9ESVJFQ1RJT05fVjFfVU5TUEVDSUZJRUQQABIaChZTT1JUX0RJUkVDVElPTl9WMV9ERVNDEAESGQoVU09SVF9ESVJFQ1RJT05fVjFfQVNDEAJC0AEKFmNvbS5vMTF5X29uZS5jb21tb24udjFCC0NvbW1vblByb3RvUAFaQ2dpdGh1Yi5jb20vbzExeS1vbmUvbzExeS1vbmUtc2RrL2dlbi9nby9vMTF5X29uZS9jb21tb24vdjE7Y29tbW9udjGiAgNPQ1iqAhFPMTF5T25lLkNvbW1vbi5WMcoCEU8xMXlPbmVcQ29tbW9uXFYx4gIdTzExeU9uZVxDb21tb25cVjFcR1BCTWV0YWRhdGHqAhNPMTF5T25lOjpDb21tb246OlYxYgZwcm90bzM");

/**
 * @generated from message o11y_one.common.v1.PageRequestV1
 */
export type PageRequestV1 = Message<"o11y_one.common.v1.PageRequestV1"> & {
  /**
   * @generated from field: optional uint32 limit = 1;
   */
  limit?: number | undefined;

  /**
   * @generated from field: optional string page_token = 2;
   */
  pageToken?: string | undefined;
};

/**
 * Describes the message o11y_one.common.v1.PageRequestV1.
 * Use `create(PageRequestV1Schema)` to create a new message.
 */
export const PageRequestV1Schema: GenMessage<PageRequestV1> = /*@__PURE__*/
  messageDesc(file_o11y_one_common_v1_common, 0);

/**
 * @generated from message o11y_one.common.v1.PageResponseV1
 */
export type PageResponseV1 = Message<"o11y_one.common.v1.PageResponseV1"> & {
  /**
   * @generated from field: optional string next_page_token = 1;
   */
  nextPageToken?: string | undefined;

  /**
   * @generated from field: bool has_more = 2;
   */
  hasMore: boolean;

  /**
   * @generated from field: uint64 total_count = 3;
   */
  totalCount: bigint;

  /**
   * @generated from field: string cursor_semantics = 4;
   */
  cursorSemantics: string;

  /**
   * @generated from field: bool total_count_approximate = 5;
   */
  totalCountApproximate: boolean;

  /**
   * @generated from field: string total_count_semantics = 6;
   */
  totalCountSemantics: string;
};

/**
 * Describes the message o11y_one.common.v1.PageResponseV1.
 * Use `create(PageResponseV1Schema)` to create a new message.
 */
export const PageResponseV1Schema: GenMessage<PageResponseV1> = /*@__PURE__*/
  messageDesc(file_o11y_one_common_v1_common, 1);

/**
 * @generated from message o11y_one.common.v1.SortSpecV1
 */
export type SortSpecV1 = Message<"o11y_one.common.v1.SortSpecV1"> & {
  /**
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * @generated from field: o11y_one.common.v1.SortDirectionV1 direction = 2;
   */
  direction: SortDirectionV1;
};

/**
 * Describes the message o11y_one.common.v1.SortSpecV1.
 * Use `create(SortSpecV1Schema)` to create a new message.
 */
export const SortSpecV1Schema: GenMessage<SortSpecV1> = /*@__PURE__*/
  messageDesc(file_o11y_one_common_v1_common, 2);

/**
 * @generated from enum o11y_one.common.v1.SortDirectionV1
 */
export enum SortDirectionV1 {
  /**
   * @generated from enum value: SORT_DIRECTION_V1_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SORT_DIRECTION_V1_DESC = 1;
   */
  DESC = 1,

  /**
   * @generated from enum value: SORT_DIRECTION_V1_ASC = 2;
   */
  ASC = 2,
}

/**
 * Describes the enum o11y_one.common.v1.SortDirectionV1.
 */
export const SortDirectionV1Schema: GenEnum<SortDirectionV1> = /*@__PURE__*/
  enumDesc(file_o11y_one_common_v1_common, 0);

